# Generated by Django 2.0.3 on 2018-04-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.CharField(max_length=100),
        ),
    ]
