# Generated by Django 2.0.3 on 2018-04-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
